frontend:
  replicaCount: 1
assetsvc:
  replicaCount: 1
dashboard:
  replicaCount: 1
kubeops:
  replicaCount: 1
postgresql:
  replication:
    enabled: false
ingress:
  enabled: true
  hostname: localhost
  tls: true
pinnipedProxy:
  enabled: true
  image:
    registry: docker.io
    repository: kubeapps/pinniped-proxy
    tag: latest
    pullPolicy: IfNotPresent
